import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Currency extends javax.swing.JFrame {

    /**
     * Creates new form Currency
     */
    public Currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox<>();
        from = new javax.swing.JComboBox<>();
        amt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel1.setBackground(java.awt.SystemColor.textHighlight);
        jpanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FROM:-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TO:-");

        to.setBackground(new java.awt.Color(204, 255, 255));
        to.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        to.setForeground(new java.awt.Color(255, 0, 51));
        to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INR", "USD", "DRM", "SL", "URO" }));
        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });

        from.setBackground(new java.awt.Color(204, 255, 255));
        from.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        from.setForeground(new java.awt.Color(255, 0, 0));
        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "SL", "URO", "DRM" }));
        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        amt.setBackground(new java.awt.Color(204, 255, 255));
        amt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        amt.setText(" ");
        amt.setToolTipText("amount");
        amt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
     
        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("CONVERT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("AMOUNT:-");

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("CURRENCY CONVERTER");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 2, 14)); // NOI18N
        jLabel5.setText("©GANIT KUMAR");

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double total;
        String s1=amt.getText().toString();
        if(s1==null || s1.isEmpty() || s1.isBlank()){
         JOptionPane.showMessageDialog(this,"Please Enter Amount!");
         return;
        }
        Double amount=Double.parseDouble(s1);
       
        if(from.getSelectedItem().toString()=="USD" && to.getSelectedItem().toString()=="INR"){
            total=amount * 82.42;
                   JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"₹");
        }else if(from.getSelectedItem().toString()=="USD" && to.getSelectedItem().toString()=="SL"){
            total=amount * 365.16;
                    JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"RS");
        }else if(from.getSelectedItem().toString()=="USD" && to.getSelectedItem().toString()=="URO"){
            total=amount * 1.03;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"€");
        }else if(from.getSelectedItem().toString()=="USD" && to.getSelectedItem().toString()=="DRM"){
            total=amount * 3.67;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"د.إ");
        }
         if(from.getSelectedItem().toString()=="INR" && to.getSelectedItem().toString()=="USD"){
            total=amount * 0.012;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"$");
        }else if(from.getSelectedItem().toString()=="INR" && to.getSelectedItem().toString()=="SL"){
            total=amount * 4.43;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"RS");
        }else if(from.getSelectedItem().toString()=="INR" && to.getSelectedItem().toString()=="URO"){
            total=amount * 0.012;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"€");
        }else if(from.getSelectedItem().toString()=="INR" && to.getSelectedItem().toString()=="DRM"){
            total=amount * 0.045;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"د.إ");
        }
         if(from.getSelectedItem().toString()=="SL" && to.getSelectedItem().toString()=="INR"){
            total=amount * 0.23;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"₹");
        }else if(from.getSelectedItem().toString()=="SL" && to.getSelectedItem().toString()=="USD"){
            total=amount * 0.0027;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"$");
        }else if(from.getSelectedItem().toString()=="SL" && to.getSelectedItem().toString()=="URO"){
            total=amount * 0.0028;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"€");
        }else if(from.getSelectedItem().toString()=="SL" && to.getSelectedItem().toString()=="DRM"){
            total=amount * 0.010;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"د.إ");
        }
        if(from.getSelectedItem().toString()=="URO" && to.getSelectedItem().toString()=="INR"){
            total=amount * 80.12;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"₹");
        }else if(from.getSelectedItem().toString()=="URO" && to.getSelectedItem().toString()=="SL"){
            total=amount * 354.97;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"RS");
        }else if(from.getSelectedItem().toString()=="URO" && to.getSelectedItem().toString()=="USD"){
            total=amount * 0.97;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"$");
        }else if(from.getSelectedItem().toString()=="URO" && to.getSelectedItem().toString()=="DRM"){
            total=amount * 3.57;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"د.إ");
        }
         if(from.getSelectedItem().toString()=="DRM" && to.getSelectedItem().toString()=="INR"){
            total=amount * 22.44;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"₹");
        }else if(from.getSelectedItem().toString()=="DRM" && to.getSelectedItem().toString()=="SL"){
            total=amount * 99.42;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"RS");
        }else if(from.getSelectedItem().toString()=="DRM" && to.getSelectedItem().toString()=="URO"){
            total=amount * 0.28;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"€");
        }else if(from.getSelectedItem().toString()=="DRM" && to.getSelectedItem().toString()=="USD"){
            total=amount * 0.27;
                     JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+total.toString()+"$");
        }
         if(from.getSelectedItem().toString()==to.getSelectedItem().toString()){
             JOptionPane.showMessageDialog(this, "YOUR CURRENCY AFTER CONVERT IS:- "+amount.toString()+" "+to.getSelectedItem().toString());
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables
}
